[tool.poetry]
name = "content-type-converter"
version = "0.1.0"
description = "Convert HTTP POST `Content-Type`, for instance from `application/x-www-form-urlencoded` to `application/json`."
authors = ["Emilien Klein <emilien@klein.st>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
